# Model parameters
model_params:
  num_trials: 250
  beta1: 1.0
  beta4: 1.0
  gamma1: 1.0
  gamma4: 0.0
  alpha1: 10.0
  alpha4: 10.0
  b1: 0.5
  b4: 0.5
  g1: 0.5
  g4: 0.0
  sigma1: 0.07
  sigma4: 0.07
  
noise_params:
  tau_f:  0.005
  sigma_f: 0.01
  noise_potential: 0.05 # 0.05
  noise_firing_rate: 0.01 # 0.01
  GR_noise: true
  delta_tau: 3.0 # 3 * tau
  noise_sigma: 0.0025 #0.5    # Amplitude of low-pass filtered noise # 2.0 for sigma = 0.025
  noise_tau: 0.075     # Time constant of low-pass filter in seconds # 0.25 for sigma = 0.025
  low_pass_add: True

Gain_modulation:
  Feedback_gain:
    enabled: True
    gamma_vals: [0.25,0.5,0.75,1.0]
    t_span: [0, 6]

  Input_gain_beta1:
    enabled: true
    beta1_vals: [0.5, 0.75, 1.0, 1.25, 1.5]
    t_span: [0, 6]

Communication:
  Feedback_gain:
    enabled: True
    gamma_vals: [1.0]
    c_vals: [ 1.0]
    t_span: [0, 6]
    save_data: true

  Input_gain_beta1:
    enabled: false
    beta1_vals: [0.5,1.0]
    c_vals: [0.032]
    t_span: [0, 6]
    save_data: true

Power_spectra:
  Feedback_gain:
    enabled: True
    gamma_vals: [1.0]
    # c_vals: [1.0,0.5,0.25,0.125,0.064,0.032]
    c_vals: [0.01,0.025,0.037,0.061,0.097,0.163,0.359,0.503,0.72]
    t_span: [0, 5]
    save_data: true
    
  Input_gain_beta1:
    enabled: false
    beta1_vals: [0.9]
    # c_vals: [1.0,0.5,0.25,0.125,0.064,0.032]
    c_vals: [0.025,0.037,0.061,0.097,0.163,0.359,0.503,0.72]
    t_span: [0, 6]
    save_data: true

Coherence:
  Feedback_gain:
    enabled: True
    gamma_vals: [1.0]
    # c_vals: [0.032,0.064,0.125,0.25,0.5,1.0]
    c_vals: [0.025,0.037,0.061,0.097,0.163,0.359,0.503,0.72]
    t_span: [0, 6]

  Input_gain_beta1:
    enabled: true
    beta1_vals: [0.9]
    # c_vals: [0.032, 0.064, 0.125, 0.25, 0.5, 1.0]
    c_vals: [0.025,0.037,0.061,0.097,0.163,0.359,0.503,0.72]
    t_span: [0, 6]

