# Model parameters
model_params:
  num_trials: 250
  beta1: 1.0
  beta4: 1.0
  gamma1: 1.0
  gamma4: 0.0
  alpha1: 10.0
  alpha4: 10.0
  b1: 0.5
  b4: 0.5
  g1: 0.5
  g4: 0.0
  sigma1: 0.1
  sigma4: 0.1
  
noise_params:
  noise_potential: XXXX
  noise_firing_rate: XXXX
  GR_noise: XXXX
  delta_tau: XXXX # 3 * tau
  noise_sigma: XXXX    # Amplitude of low-pass filtered noise
  noise_tau: XXXX     # Time constant of low-pass filter in seconds
  low_pass_add: XXXX     # Whether to add low-pass filtered noise

Gain_modulation:
  Feedback_gain:
    enabled: true
    gamma_vals: [0.0,0.25,0.50,0.75,1.0,1.10]
    t_span: [0, 5]

  Input_gain_beta1:
    enabled: true
    beta1_vals: [1.0, 1.25, 1.5, 1.75]
    t_span: [0, 6]

Communication:
  Feedback_gain:
    enabled: True
    gamma_vals: [0.5,1.10]
    c_vals: [ 1.0]
    t_span: [0, 6]
    save_data: true

  Input_gain_beta1:
    enabled: False
    beta1_vals: [1.0, 1.5]
    c_vals: [0.032, 0.064, 0.125, 0.25, 0.5, 1.0]
    t_span: [0, 6]
    save_data: true

Power_spectra:
  Feedback_gain:
    enabled: true
    gamma_vals: [0.0,0.25,0.50,0.75,0.85,0.90,0.95,1.0,1.05,1.10]
    c_vals: [1.0,0.5,0.25,0.125,0.064,0.032]
    t_span: [0, 5]
    save_data: true
    
  Input_gain_beta1:
    enabled: False
    beta1_vals: [0.5,0.75,1.0,1.25,1.50]
    c_vals: [0.032, 0.064, 0.125, 0.25, 0.5, 1.0]
    t_span: [0, 6]
    save_data: true

Coherence:
  Feedback_gain:
    enabled: True
    gamma_vals: [0.0,0.25,0.50,0.75,0.85,0.90,0.95,1.0,1.05,1.10]
    c_vals: [0.032,0.064,0.125,0.25,0.5,1.0]
    t_span: [0, 6]
    save_data: true

  Input_gain_beta1:
    enabled: False
    beta1_vals: [0.5,0.75,1.0,1.25,1.50]
    c_vals: [0.032, 0.064, 0.125, 0.25, 0.5, 1.0]
    t_span: [0, 6]
    save_data: true

